/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "[BUY": "[购买",
    "[ OPTIONS ▲ ]": "[ 选项 ▲ ]",
    "[ OPTIONS ▼ ]": "[ 选项 ▼ ]",
    "[ PARTY VAULT ]": "[ 队伍金库 ]",
    "[ GLOBAL UPGRADES ]": "[ 全局升级 ]",
    "[ Credits ]": "[ 鸣谢 ]",
    "[ Load Save ]": "[ 加载存档 ]",
    "[ Export as File ]": "[ 导出为文件 ]",
    "[ Copy to Clipboard ]": "[ 复制到剪贴板 ]",
    "[ Save to Browser ]": "[ 保存到浏览器 ]",
    "[ Clear Browser Save ]": "[ 清除浏览器存档 ]",
    "[ WILD WILDERNESS ]": "[ 原始荒野 ]",
    "[ FLEE ]": "[ 逃跑 ]",
    "[ KOBOLD ]": "[ 地精 ]",
    "[ RETRY ]": "[ 重试 ]",
    "[ SIDEQUEST ]": "[ 支线任务 ]",
    "[ FIGHTER ]": "[ 战士 ]",
    "[ STATISTICS ]": "[ 统计 ]",
    "[ CHARACTERS ]": "[ 角色 ]",
    "[ CHARACTER STATS ]": "[ 角色属性 ]",
    "[ ACTIVITY LOG ]": "[ 活动日志 ]",
    "[ >>> Hunt & Gather <<< ]": "[ >>> 狩猎 & 采集 <<< ]",
    "[ >>> Complete Bounty <<< ]": "[ >>> 完成赏金 <<< ]",
    "[ UPGRADES ]": "[ 升级 ]",
    "---[ PARTY ]---": "---[ 队伍 ]---",
    "-- No activity entries --": "-- 没有活动记录 --",
    "WARN": "警告",
    "RARE": "稀有",
    "SUCCESS": "成功",
    "Gold": "金币",
    "Fighter": "战士",
    "ERROR": "错误",
    "Contracted Hirelings": "雇佣兵",
    "Better Bounties": "更好的赏金",
    "insufficient resources": "资源不足",
    "Gold/Bounty   :": "金币/赏金   :",
    "A mercenary looking to get by, completing odd jobs and learning about the world around him.": "一个一心想要谋生的人，他从事零散的工作，同时也在了解周围的世界。",
    "INFO": "信息",
    "// PLAYTIME": "// 游戏时长",
    "╔═ STATISTICS ═╗": "╔═ 统计 ═╗",
    "Time Played": "游戏时长",
    "+[ OPTIONS ]+": "+[ 选项 ]+",
    "// DISPLAY": "// 显示",
    "// IMPORT": "// 导入",
    "// SAVE": "// 保存",
    "You ventured forth and found gold. (": "你毅然前行，最终发现了金币。(",
    "// HERO BUTTON PRESSES": "// 英雄按钮点击次数",
    "// LIFETIME CURRENCY EARNED": "// 终身所获货币收入",
    "Manual": "手动",
    "Total": "总计",
    "-- No matching entries --": "-- 暂无匹配的记录 --",
    "!! WARNING !!": "!! 警告 !!",
    "[ NO — KEEP SAVE ]": "[ 否 — 保留存档 ]",
    "[ YES — ERASE SAVE ]": "[ 是 — 删除存档 ]",
    "Game saved to browser cache.": "游戏已保存至浏览器缓存中。",
    "Save data copied to clipboard.": "存档已复制到剪贴板中了。",
    "Save file exported.": "存档文件已导出。",
    "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|\n|  DELETE BROWSER SAVE?   |\n|  This cannot be undone. |\n|_________________________|": "|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|\n|  删除浏览器存档?   |\n|  此操作不可撤销. |\n|_________________________|",
    "this browser and the page will reload.": "此浏览器及页面将重新加载。",
    "Your saved progress will be permanently erased from": "您保存的进度将被永久删除。",
    "[ Close ]": "[ 关闭 ]",
    "+[ CREDITS ]+": "+[ 鸣谢 ]+",
    "Paste a save string into the import box first.": "首先将存档字符串粘贴到导入框中。",
    "Game state saved to browser cache.": "游戏状态已保存到浏览器缓存。",
    "[UNLOCK:": "[解锁:",
    "GLOBAL": "全局",
    "A perceptive folk, and a warden of the woods. Even if she hunts no prey, she manages to always bring something else home.": "洞悉万物的林间住民，亦是森林的守望者。即便未曾狩猎猎物，她总能带回别样收获。",
    "Beast Meat": "野兽肉块",
    "Herb": "草药",
    "Ranger": "游侠",
    "RANGER": "游侠",
    "+1 Herb every 5 seconds per level": "每级每5秒产出1份草药",
    "+1 Raw Beast Meat every 5 seconds per level": "每级每5秒产出1份生兽肉",
    "+3% chance to double base herbs": "基础草药产出翻倍概率+3%",
    "+3% successful hunt chance": "狩猎成功率+3%",
    "Baited Traps": "诱饵陷阱",
    "Beast Success :": "狩猎成功率：",
    "Better Tracking": "高效追踪",
    "Herb Double   :": "草药翻倍：",
    "Hovel Garden": "小屋菜园",
    "More Herbs": "草药增量",
    "// MILESTONES": "// 里程碑",
    "You targeted a beast but it escaped": "你锁定了野兽目标，但猎物逃脱了",
    "You targeted herbs and foraged some": "你搜寻草药，并采集到若干资源",
    "You tracked a beast and claimed its meat": "你追踪野兽猎物，成功获取了它的肉",
    "[MAXED]": "[满级]",
    "You ventured forth and found gold": "你外出探索，寻得了一些金币",
    "Insightful Contracts": "洞察力合同",
    "[HIRE:": "[雇佣:",
    "Avail:": "可用:",
    "Hire a Jack of All Trades": "雇佣一名全能型人才",
    "Hire a Jack to auto-click a hero button once per second": "雇佣一个全能型人才，让他每秒自动点击一次“英雄”按钮。",
    "XP/Bounty    :": "经验/悬赏    :",
    "Apothecary": "药剂师",
    "Adventurers of all types stop in for a potion or two every now and then. He can give everyone something that itches that *personal* itch.": "各种类型的冒险者们时不时会来这里喝上几杯药水。他能够为每个人提供能解决他们各自“个人”烦恼的解药。",
    "Unlock Sidequests": "解锁支线任务",
    "Unlocks character specific sidequests": "解锁角色特定的支线任务",
    "[ >>> Distill <<< ]": "[ >>> 蒸馏 <<< ]",
    "+1 gold per potion distilled": "每炼制一瓶药剂，额外获得1金币",
    "+1 potion and -1 herb every 10 seconds. (toggleable)": "每10秒产出1瓶药剂，消耗1份药草（可开关）",
    "+4% chance to save herbs when distilling": "炼制药剂时，药草留存概率+4%",
    "+5% chance to roll both herb AND beast": "同时触发药草与野兽产出的概率+5%",
    "APOTHECARY": "药剂师",
    "Fermentation Vats": "发酵木桶",
    "Gold/Brew    :": "金币/酿造产出：",
    "Herb Save Chance :": "药草留存概率：",
    "Herbs/Brew   :": "药草/酿造消耗：",
    "Potion Base": "药剂基底",
    "Potion Marketing": "药剂行销",
    "Potion of Cat's Eye": "猫眼药剂",
    "Potion Titration": "药剂滴定改良",
    "A seasoned chef who sources only the finest ingredients. People travel from far and wide seeking these exquisite tastes. Few are prepared for what they'll find...": "一位经验丰富的厨师，只选用最优质的食材。人们从四面八方赶来，只为品尝这些美味佳肴。但很少有人能预料到他们会遇到什么……",
    "Culinarian": "烹饪师",
    "[ >>> Source Ingredients <<< ]": "[ >>> 来源成分 <<< ]",
    "-1% spice purchase cost per level": "每级香料购买价格降低1%",
    "[ Wholesale Spices: OFF ]": "[ 香料批发：关闭]",
    "[ Wholesale Spices: ON ]": "[ 香料批发：开启]",
    "[ Fermentation Vats: OFF ]": "[ 发酵木桶：关闭]",
    "[ Fermentation Vats: ON ]": "[ 发酵木桶：开启]",
    "+1 spice per click, purchased at a discount!": "每次点击获得1份香料，享受折扣采购！",
    "CULINARIAN": "烹饪师",
    "Each Baited Trap produces +1 raw beast meat per level of Spiced Bait": "每级香辛诱饵天赋，可使每个诱饵陷阱额外产出1份生兽肉",
    "Gold/Spice   :": "金币/香料：",
    "Potion of Glibness": "巧言药剂",
    "Spice": "香料",
    "Spice/Click  :": "点击/香料产出：",
    "Spiced Bait": "香辛诱饵",
    "Wholesale Spices": "香料批发",
    "Wholesale Total  :": "批发总量：",
    "You sourced exotic spices": "你获取了珍稀异域香料",
    "You brewed a potion and recovered herbs! (": "你配制了一剂药水并采集到了一些草药！(",
    "Hireling's Hirelings": "雇佣者的雇佣者",
    "Each hireling gets this many hirelings, also generating +1 gold per sec": "每位雇佣兵会获得这么多的雇佣兵数量，并且每秒还能额外获得 1 金币。",
    ", have": ", 拥有",
    "Not enough gold to gather spices. Need": "没有足够的金币来收购香料了。需要",
    "[UPGRADE:": "[升级:",
    "[> ATTACK ]": "[> 攻击 ]",
    "-- Ready to fight --": "-- 准备战斗 --",
    "+1 HP per potion heal": "每使用药剂恢复生命，生命值+1",
    "+1 max hit in combat": "战斗最大单次伤害+1",
    "★ SIDEQUESTS UNLOCKED! Character-specific challenges are now available.": "★ 支线任务已解锁！现已开放专属角色挑战。",
    "Attack Damage    :": "攻击伤害：",
    "Auto-heal to full HP with potions after each victory at a reduced efficiency": "每场战斗胜利后，会自动用药剂回满生命值，效果有所衰减",
    "Hireling's Hirelings upgraded to Lv.1.": "雇工的随从已升级至1级。",
    "Jack'd Up": "强化人才",
    "Jacks click 50% faster": "地精点击效率提升50%",
    " Bait": "诱饵",
    " drop more parts when baited with meat": "掉落素材更多，当使用肉类作为诱饵时",
    "MAX": "满级",
    "Potion of Fortitude": "坚韧药剂",
    "Sharper Swords": "锋利长剑",
    "Short Rest": "短暂休憩",
    "Stronger Kobolds": "强化地精",
    "You can seek out stronger kobolds. They grow...": "你可以搜寻更强的地精。它们正在不断蜕变……",
    "-- New enemy! --": "-- 新敌人! --",
    " Left Ear": "左耳",
    " defeated!": " 被击败了!",
    "FIGHTER": "战士",
    "The Kobold drops a Kobold Ear! (": "地精 掉落了一个 地精耳朵！(",
    "-- Resumed --": "-- 已返回 --",
    "s drop more parts when baited with meat": "掉落更多的零件，当用肉作诱饵时",
    "The Slow Blade": "慢刃",
    "+1 minimum hit in combat": "战斗最小攻击伤害+1",
    "A Mutual kill!": "同归于尽！",
    "Mutual kill! Loot still collected": "双方阵亡！依旧可拾取战利品",
    "!! DEFEATED !!": "!! 战败 !!",
    "[ ALCHEMY TABLET ]": "[ 炼金石板 ]",
    "[ BREW ]": "[ 酿造 ]",
    "[ GET COOKIN' ]": "[ 开火烹饪 ]",
    "[ HUNTING GROUNDS ]": "[ 狩猎场 ]",
    "[ START POTION ]": "[ 开始炼药 ]",
    "[ TEST KITCHEN ]": "[ 试验厨房 ]",
    "+1 concentrated potion, with a risk of failure (toggleable)": "额外产出1瓶浓缩药剂，伴随失败风险（可开关）",
    "+1 hearty meal per unused guess on a successful recipe": "配方解锁成功时，每剩余一次猜测次数，额外获得1份丰盛餐食",
    "+1 resource tile per level": "每级额外解锁1块资源地块",
    "Abundant Lands": "丰饶之地",
    "Bountiful Lands": "沃土良田",
    "Bubbling Brew": "沸腾酿造",
    "costs 4 of each:": "各消耗4份：",
    "costs 50": "消耗50",
    "Costs 9": "消耗9",
    "need 4 more": "还需4份",
    "per scout.": "每名斥候生效。",
    "Potion Dilution": "药剂稀释",
    "Resource gain is multiplied by the number of successful finds": "资源获取量根据探索成功次数倍率加成",
    "Reveal 3 of 9 hidden boxes.": "揭露9个隐藏格子中的3个。",
    "Skilled brewing will award bonus progress": "精湛酿造可获得额外进度加成",
    "Waste Not": "物尽其用",
    "// KOBOLDS SLAIN": "// 已击杀地精",
    "S I D E Q U E S T": "支线任务",
    "Sidequests": "支线任务",
    "Kobold": "地精",
    "A Lady doesn't need to always lurk in the shadows.": "淑女不必永远隐匿于阴影之中。",
    "Apothecary: Jack Bead Found": "药剂师：已找到人才宝珠",
    "THIEF": "小偷",
    "Thief": "小偷",
    "Times Defeated": "战败次数",
    "Total Kills": "总击杀数",
    "[NONE]": "[无]",
    "[ALL]": "[全部]",
    "[ Recall all Jacks ]": "[ 召回所有人才 ]",
    "Bigger Bubbles": "更大的泡沫",
    "Increase the size of the Bubbling zone": "增大气泡区域的大小",
    "Fighter: Jack Bead Found": "战士：发现了人才宝珠",
    "Potions Drank": "饮用药水",
    "--- OUT OF ZONE ---": "--- 超出区域 ---",
    ">>> IN ZONE <<<": ">>> 区域内 <<<",
    "Click on beat to raise quality!": "点击节拍提升品质！",
    "Concentrated Potion Base": "浓缩药剂基底",
    "Concentration": "浓缩度",
    "Potion concentrated": "药剂已浓缩",
    "empty": "空",
    "Found:": "发现:",
    "Choose 3 boxes...": "选择 3 个箱子...",
    "-- or click any cell --": "-- 或点击任意格子 --",
    "-- Round complete --": "-- 回合完成 --",
    "picks remaining:": "剩余次数：",
    "Pixie Dust": "精灵粉尘",
    "Pixie!": "小精灵！",
    "Raw Meat": "生肉",
    "Fleeing...": "逃跑...",
    "Found: Nothing...": "发现: 无...",
    "*** BUBBLING ***": "*** 气泡冒出 ***",
    "Artisan": "工匠",
    "Cat's Eye     :": "猫眼:",
    "A meticulous craftsman who sees value where others see junk. It takes one with *true* sight to understand the value of the unseen.": "一位极其细心的工匠，能在别人眼中视为废品的东西中发现其价值。只有拥有真正洞察力的人才能理解那些看不见的东西所蕴含的价值。",
    "// ALCHEMY TABLET": "// 炼金术石板",
    "// HUNTING GROUNDS": "// 狩猎场地",
    "Perfect Hits": "完美命中",
    "Potion Hits": "药剂调配命中",
    "Sidequests Complete": "已完成支线任务",
    "Successful Hunts": "狩猎成功次数",
    "Unsuccessful Hunts": "狩猎失败次数",
    "\"It was one fateful day I received a particular job from a man only known as 'My Patron'. I was tasked with gathering a crew of highly skilled craftsmen for a project larger than life. I have my question, but this is a sum of money I cannot turn down.\"": "“那是我人生中一个至关重要的日子，我从一个只被称为‘我的恩人’的人那里接到了一份特别的工作。我被要求组建一支由技艺精湛的工匠组成的团队，去完成一项规模空前的项目。我有我的疑问，但这笔钱我实在无法拒绝。”",
    "[ SOCKET ]": "[ 放入 ]",
    "[CLOSE]": "[关闭]",
    "── SOCKETED ──": "── 已放入 ──",
    "── NOT YET DISCOVERED ──": "── 尚未发现 ──",
    "\"For the first time in MANY years, I was approached by an odd man who knew what he wanted. What he *Actually* wanted. Something that even I had a hard time describing...\"": "“多年以来，第一次有一位怪人主动找上我，他清楚自己想要什么，是**真正**想要的东西。那事物的奇异，连我都难以言喻……”",
    "2× resource yields from this character (stacks).": "该角色资源产出 x2（叠加）。",
    "Bead of Concentration": "凝神宝珠",
    "Bead of Distillation": "蒸馏宝珠",
    "Bead of Mastery": "精通宝珠",
    "Bead of Refinement": "精炼宝珠",
    "Bead of Seasoning": "调味宝珠",
    "Bead of Supremacy": "至尊宝珠",
    "Bead of the Alembic": "蒸馏器宝珠",
    "Bead of the Epicure": "美食家宝珠",
    "Bead of the Hearth": "炉火宝珠",
    "Bead of the Mercenary": "佣兵宝珠",
    "Bead of the Pack": "行囊宝珠",
    "Bead of the Sous Chef": "副厨宝珠",
    "Bead of the Vanguard": "先锋宝珠",
    "Bead of the Wild": "荒野宝珠",
    "Bead of Valor": "勇武宝珠",
    "Effect:": "效果：",
    "[ Auto-Solve: ON ]": "[ 自动侦查: 打开 ]",
    "[ Auto-Solve: OFF ]": "[ 自动侦查: 关闭 ]",
    "These mountain hills are confusing to travel through. I start in the northwest passage, and suddenly find myself in the north east, but I was mistaken again, it was just the south! I travel far north, just to be South west, or was it south east? Anyways, I retreat from the east all the way back west, just to head north and back to the east, a long journey! One day, next time I find myself in the south west, I'll make a straight shot east for one final trek.": "这些山丘地形复杂，难以通行。我从西北方向出发，突然发现自己身处东北方向，但我又错了，原来只是南方！我一路向北前行，结果却变成了西南方向，或者是东南方向？不管怎样，我从东边一路向西撤回，最终又向北行进，回到了东边，这是一段漫长的旅程！有一天，下次我发现自己在西南方向时，我会直接向东行进，进行最后一次的跋涉。",
    "Bead of the Pathfinder": "探路者宝珠",
    "Unlocks basic sidequest automation.": "开启基本支线任务自动化功能。",
    "Ranger: Gold Bead Found (Sidequest)": "游侠：发现金珠（支线任务）",
    "Passive": "被动",
    "Next Kobold Level:": "下一个地精等级：",
    "[ Assign Jack ]": "[ 分配人才 ]",
    "[ SNAKE KOBOLD ]": "[ 蛇地精 ]",
    " Tongue": "舌头",
    "[ Dilution: OFF ]": "[ 稀释: 关闭 ]",
    "[ Dilution: ON ]": "[ 稀释: 打开 ]",
    "+1 additional independent potion roll per level when diluting": "每进行一次稀释，每等级额外增加1次独立药剂判定次数",
    "Dilution Chance  :": "稀释概率：",
    "Dilution Rolls   :": "稀释判定次数：",
    "Serial Dilution": "连续稀释",
    "[ BEGIN RITUAL ]": "[ 开始仪式 ]",
    "[ BEGIN ETCHING ]": "[ 开始刻蚀 ]",
    "[ SUBMIT ]": "[ 提交 ]",
    "[ Recall Button Jacks ]": "[ 召回所有人才 ]",
    "[ Recall Sidequest Jacks ]": "[ 召回支线人才 ]",
    "[ CLEAR ]": "[ 清除 ]",
    "HISTORY": "历史",
    "Dilution Successes": "稀释成功",
    "Spice Discount   :": "香料折扣:",
    "Necromancer": "亡灵法师",
    "A scholar of the unholy arts. He commands the boundary between life and death, yet fails to connect with the living around him.": "一位从事邪恶技艺的学者。他能够掌控生死的界限，但却无法与身边的生者建立联系。",
    "xp": "经验值",
    "spice,": "香料,",
    "potions": "药水",
    "GOLD": "金币",
    "herb,": "草药,",
    "herbs": "草药",
    "gemstones": "宝石",
    "gemstone": "宝石",
    "mana": "法力",
    "bone": "骨头",
    "beast,": "野兽,",
    "beast": "野兽",
    "beast meat": "野兽肉块",
    "brimstone": "硫磺",
    "kobold-tongue,": "地精舌头,",
    "Crack the safe by finding the sweet spot.": "找准最佳点位，破解保险箱。",
    "dossiers": "档案卷宗",
    "Draw the shortest binding circle through all soul anchors.": "画出能贯穿所有灵魂锚点的最短束缚法阵。",
    "Examine 6 gemstones and pick the finest one.": "检视6颗宝石，挑选品质最佳的一颗。",
    "Illicit Goods": "违禁物品",
    "per heist.": "每次掠夺。",
    "precious metal": "贵金属",
    "Prices fluctuate every few seconds.\nBuy low!": "价格每几秒就会波动一次。低买高卖！",
    "Repeat the flashing symbols!\nConcentrate...": "复刻闪烁的符文图案！集中精神……",
    "Dilution Failures": "稀释失败",
    "Culinarian: Jack Bead Found": "厨师长：找到人才宝珠",
    "[ COOK AGAIN ]": "[ 再次烹饪 ]",
    "Hearty Meal": "丰盛的餐食",
    "INGREDIENTS": "配料",
    "\"My favorite guest, a long time Patron came to me with an odd request today. The flavors unconventional, the portions... excessive. This is no catered meal, but a feast for some sort of devouring animal!\"": "“我最喜爱的那位常客今天找我提出了一个奇特的要求。菜品的口味与众不同，分量……”过度的。这可不是什么精心准备的饭菜，而是一场专为某种食肉动物准备的盛宴！\"",
    "Merchant": "商人",
    "A cunning dealer who trades in goods others dare not touch. His connections span every dark corner of the nation.": "一个狡猾的商人，专门从事那些他人不敢碰的生意。他的人脉遍布全国的每一个阴暗角落。",
    "Artificer": "艺术家",
    "A scholar of arcane constructs. She strives for perfection, but for some reason refuses to achieve it. Her lab is surrounded by parts of nearly complete masterpieces.": "一位研究神秘构造的学者。她追求完美，但不知为何却始终无法达成这一目标。她的实验室里摆满了近乎完美的成品部件。",
    "// TEST KITCHEN": "// 测试厨房",
    "Recipes Failed": "食谱失败",
    "Recipes Found": "食谱发现",
    "-- Escaped! --": "-- 逃跑了! --",
    "Apothecary begins brewing": "药剂坊开始酿造",
    "Dilution success! (": "稀释成功！",
    "The Fighter fled from combat.": "战士逃离了战斗",
    " Hair": "毛发",
    "-1 second appraisal timer per level": "每等级鉴定计时减少1秒",
    "[ >>> Appraisal <<< ]": "[ 鉴定 ]",
    "[ >>> Break & Enter <<< ]": "[ 撬锁入室 ]",
    "[ BIG HEIST ]": "[ 大型劫案 ]",
    "[ FACETING STATION ]": "[ 刻面加工台 ]",
    "// BIG HEIST": "// 大型劫案",
    "+1 gold equal per dossier collected, per level": "每等级每份收集的档案额外等值1金币",
    "+1 jewelry for each gem in the round with a quality above 50%": "本轮中每颗品质超过50%的宝石，额外获得1件珠宝",
    "+1 max detection tolerance per level": "每等级最大侦测容忍度+1",
    "+1 max dossier yield per level": "每等级档案最大产出+1",
    "+1 max gemstone and precious metal yield per level": "每等级宝石与贵金属最大产出+1",
    "+1% secondary drop chance and +1% gold per kill per level": "每等级次级掉落概率+1%，每次击杀金币+1%",
    "+1% thieving success chance per level": "每等级偷窃成功率+1%",
    "+10% lucky gem bonus per level": "每等级幸运宝石加成+10%",
    "+2% chance per level to find a treasure chest while hunting": "每等级狩猎时有2%概率发现宝箱",
    "+3° sweet spot arc per level": "每等级最佳点位弧度增加3度",
    "A pixie, if present, will call out to a friend for help...": "若有小精灵在场，它会呼叫同伴前来协助……",
    "Allows the discovery of one additional relic!": "可额外多发现一件遗物！",
    "Appraisal Time :": "鉴定时间：",
    "ARTISAN": "工匠",
    "Bag of Holding": "储物行囊",
    "Culinarian: Blue Bead Found": "烹饪达人：已发现蓝色宝珠",
    "Dial ticks now give hints as to where the sweet spot is": "转盘刻度现在会提示最佳点位位置",
    "Dossier": "档案",
    "Double Dip": "双重收益",
    "Each Hovel Garden produces +1 herb per level of Ornate Herb Pots": "每间小屋花园，华丽药草盆每等级额外产出1株草药",
    "Fairy Hostage": "精灵人质",
    "Faster Appraising": "鉴定加速",
    "First Relic Found": "首次发现遗物",
    "Flow State": "行云状态",
    "Gem Hunter": "宝石猎手",
    "Gemstone": "宝石",
    "Gemstone Yield :": "宝石产出：",
    "Gilded Blade": "鎏金之刃",
    "Gold Yield     :": "金币产出：",
    "Good Enough": "尚可品质",
    "Heists Failed": "劫案失败次数",
    "Increased maximum gold and treasure yield": "提升金币与宝物最大产出量",
    "Locked In": "专注锁定",
    "Lucky Gem Bonus:": "幸运宝石加成：",
    "Lucky Gems": "幸运宝石",
    "Marks failed crack positions on the dial with a tick": "在转盘上用记号标记已失败的破解位置",
    "Metal Yield    :": "金属产出：",
    "Meticulous Planning": "缜密规划",
    "need 20 treasure (have 10)": "需20件宝物（当前拥有10件）",
    "Ornate Herb Pots": "华丽药草盆",
    "Perfect clicks add +5% dilution success chance": "完美点击可额外增加5%稀释成功率",
    "Perfect Potions": "完美药剂",
    "Plentiful Plundering": "掠夺丰盈",
    "Potion Misses": "药剂炼制失败",
    "Potion of Cat's Ears": "猫耳药剂",
    "Potion of Sticky Fingers": "妙手药剂",
    "Potion of the Cat's Paw": "猫爪药剂",
    "Precious Metal": "贵金属",
    "Ranger: Blue Bead Found": "游侠：已发现蓝色宝珠",
    "Relic": "遗物",
    "Relic Hunter": "遗物猎手",
    "Relics Found   :": "已发现遗物：",
    "Reveals cryptic progress messages when completing gold bead challenges": "完成金色宝珠挑战时会揭示隐秘进度提示",
    "Safes Cracked": "已破解保险箱数量",
    "Save data imported and applied.": "存档数据已导入并生效。",
    "Secondary Chance      :": "次级掉落概率：",
    "Select the second best gem as well, but only if you find the best first!": "必须先选出最优宝石，才可再选取次优宝石！",
    "Spider Kobold": "蜘蛛地精",
    "Stand Out Selection": "出众甄选",
    "Stunned!": "僵直眩晕！",
    "Success Chance :": "成功率：",
    "Synaptical Potions": "神经药剂",
    "The Best gemstone is even better": "最优宝石品质进一步提升",
    "The first ingredient in the recipe is always revealed": "配方首个材料永远自动揭示",
    "Treasure": "宝物",
    "Treasure Chest": "宝箱",
    "Treasure Cost  :": "宝物所需数量：",
    "Treasure Yield :": "宝物产出：",
    "Unlock the synaptical potion formula": "解锁神经药剂配方",
    "Vanishing Powder": "遁形粉末",
    "Vintage Cookbook": "复古食谱",
    "ARTISAN": "工匠",
    "Dossier": "档案卷宗",
    "Gemstone": "宝石",
    "Perfect clicks add +5% dilution success chance": "完美点击额外增加5%稀释成功率",
    "Perfect Potions": "完美药剂",
    "Precious Metal": "贵金属",
    "Relic": "遗物",
    "Synaptical Potions": "神经药剂",
    "THIEF": "盗贼",
    "Treasure": "宝物",
    "Unlock the synaptical potion formula": "解锁神经药剂配方",
    "The Chef welcomes guests from all over the nation to charm them with rare flavors and exotic ingredients. His secrets are his own, and his culinary rivals are always looking to uncover his secret ingredient. But the truth is, there's no secret. It's al in the preparation.": "这位厨师热情地欢迎全国各地的宾客，用独特的风味和异国食材来吸引他们。他的秘诀只属于他自己，而他的烹饪对手们总是试图找出他的“秘密配料”。但事实是，并没有所谓的“秘密”。关键在于烹饪的准备工作。",
    "The Ranger maneuvers through the wilds effortlessly. In normal times, they identify and procure valuable herbs, mushrooms, and other forageable goods. If they're lucky, they'll bring home a quality hunt, fetching the real big bucks.": "这位游骑兵在荒野中行动自如。在平常情况下，他们会识别并获取珍贵的草药、蘑菇以及其他可食用的物品。如果运气好的话，他们还能带回一回成功的狩猎，从而赚得丰厚的报酬。",
    "[BUY:": "[购买:",
    "\"I've discovered a nearly perfect formula for my latest potion concoction! It turns out, you can maximize herb yield by steeping it alllmossst all the way to completion, reducing it down to nearly frozen temps, and then finishing it off with a perfect level of attention. Brilliant!": "“我终于找到了制作最新药剂的近乎完美的配方！结果发现，要想最大限度地提高草药的产量，就得将其一直浸泡到完全完成，将其浓缩至接近冰点的温度，最后还要给予它恰到好处的精心照料。”太棒了！",
    "\"I kill and I kill, one by one, by two, by three, by five. They fall after each other, and here I stand, a mercenary at best. Is this what I was destined for? Brutal kobold slaughter until a swarm does me in?\"": "“我不断地杀戮，一次又一次，两三个一组，五个一组地杀。他们一个接一个地倒下，而我却站在一旁，最多只能算个雇佣兵罢了。这就是我命中注定要经历的吗？残忍地屠杀那些小矮人，直到一群小矮人把我干掉？”\"",
    "\"A mercenary reached out to on behalf of some sort of \"Patron\". I was requested to gather large quantities of beast flesh, for some reason. Perhaps this is some sort of Lord, looking to throw a feast? I should gather some edible herbs then!\"": "“一名雇佣兵代表某个‘赞助人’前来找我。他们要求我收集大量兽类的肉，不知为何。也许这是某位大人物，想要举办一场宴会？那我应该收集一些可食用的草药才行！”\"",
    "\"These fools are so unrefined, they couldn't tell a fine potion from their spit! To think, I could simply double my profit margins by selling them some watered down garbage!\"": "“这群庸人毫无见识，连上等药剂和劣质次品都分辨不出！索性卖点兑水的劣质货色，就能轻轻松松把利润翻上一倍！”",
    "2× resource yields from this character.": "该角色资源产出翻倍。",
    "Bead of Industry": "实业宝珠",
    "Bead of Precision": "精准宝珠",
    "Bead of Shadows": "暗影宝珠",
    "Bead of the Fence": "篱障宝珠",
    "Bead of the Ghost": "幽影宝珠",
    "Bead of the Masterwork": "精工宝珠",
    "Bead of the Prodigy": "天才宝珠",
    "Bead of the Unseen Hand": "无形之手宝珠",
    "Belt of the Woodlands": "林地腰带",
    "Crown of Command": "统帅王冠",
    "Don't be fooled - This is not lowly thief. A Lady of the night holds the highest position in the land. Underlings do the dirty work, leaving the *real* work": "别被表象蒙蔽——她绝非普通窃贼。这位暗夜女统领身居这片土地的最高地位。手下爪牙负责脏活累活，而真正的要务则由她亲自掌控。",
    "Each assigned Jack adds +1 to the base herb yield (before doubling) and +1 bonus beast meat per hunt": "每指派一名能手，基础药草产出+1（翻倍前），每次狩猎额外获得1份兽肉。",
    "Each Jack hires hirelings, who in turn can hire hirelings": "每名能手可雇佣随从，随从还能继续雇佣下属。",
    "It's bold of one to ask such a Lady for help like this, but it's hard for someone like her to turn down such a bold request. Imagine the dirt you could gather from such an ambitious and well connected project.": "敢贸然向这位大人物求助，实属大胆。但以她的身份，很难拒绝这般果敢的请求。试想，从这样野心勃勃、人脉广博的行动中，能搜罗到多少隐秘情报。",
    "Jacks always salvage maximum metal and double the minimum gemstone yield": "能手保底打捞最大金属产量，宝石最低产出翻倍。",
    "Jacks consume 1 fewer herb per brew (min 0) and automatically dilute each brew into 2 potions": "每名能手每次炼制少消耗1份药草（最低为0），且自动将每份炼制品稀释成2瓶药剂。",
    "Jacks double their dossier yield range and steal 2 bonus treasure per successful action": "能手档案产出区间翻倍，每次行动成功额外盗取2件宝物。",
    "Masterwork Monocle of Perfection": "完美精工单片眼镜",
    "Monocle of Perfect Theurgy": "神术完美单片眼镜",
    "Ring of Shadows": "暗影戒指",
    "The Fighter stands on principle, taking up jobs in service of those in need. Money is exchanged, yes, but it's all fair at the end of the day.": "战士坚守自身原则，只为有需要之人承接委托。虽也收取报酬，但一切行事讲求公道。",
    "The jacks assigned to this sidequest will work faster.": "指派到支线任务的能手工作速度提升。",
    "You find behind a painting, a scribbled on a note. Who knows what it could mean... \"9-3-9-10-6-9-3\"": "你在一幅画作后方发现一张潦草字条，无人知晓其含义：「9-3-9-10-6-9-3」",
    "[ Unassign Jack ]": "[ 取消分配人才 ]",
    "Jewelry": "珠宝",
    "kobold tongues": "狗头人舌头",
    "Ranger sets out to scout the area": "游侠开始侦察这个地区",
    "Concentrated Potion crafted! (": "药剂已浓缩! (",
    "Ranger scouted the area: found nothing useful.": "游侠侦查了这片区域，没有发现有用的东西。",
    "Ranger scouted the area": "游侠侦查了这片区域",
    "You slipped in undetected and secured some dossier": "你悄悄地潜入了那里，并获取了一些文件资料。",
    "Close Enough": "足够接近",
    "★ Bead of the Sous Chef socketed for Culinarian! Resource yields doubled!": "★ 为厨师长准备的副厨专用扣环！资源产出翻倍！",
    "Miss!": "未命中!",
    "Loot:": "战利品:",
    "Ward XP Cost   :": "守护结界 经验成本   :",
    "Ward <<< ]": "守护结界 <<< ]",
    "Ward": "守护结界",
    "XP": "经验值",
    " Brain": "脑部材料",
    " Fang": "尖牙",
    " Feather": "羽毛",
    " Mountain Lion": "山狮",
    " Mountain Lion defeated!": "山狮 已击败！",
    " Sorcerer": "巫师",
    "-- or click any gem --": "——或点击任意宝石——",
    "-2 XP cost per ward per level (min 1)": "每级每个守护结界减少2点经验消耗（最低1点）",
    "[ >>> Exhume": "[ >>> 发掘 ]",
    "[ ACTIVE ]": "[ 主动效果 ]",
    "[ CLICK TO CRACK ]": "[ 点击开启 ]",
    "[ First Strike: ON ]": "[ 先攻：开启 ]",
    "[ FIRST STRIKE! ]": "[ 触发先攻！ ]",
    "[ HEIST AGAIN (50": "[ 再次掠夺（50 ]",
    "[ KOBOLD MOUNTAIN LION ]": "[ 狗头人山狮 ]",
    "[ Short Rest: OFF ]": "[ 短暂休整：关闭 ]",
    "[ Synaptical Potion: OFF ]": "[ 突触药剂：关闭 ]",
    "[ Vintage Cookbook: ON ]": "[ 复古食谱：开启 ]",
    "[ WELL OF SOULS ]": "[ 灵魂之井 ]",
    "// FACETING": "// 琢面雕琢",
    "// WELL OF SOULS": "// 灵魂之井",
    "+1 max bone yield per level": "每级骨头最大产出+1",
    "+1 max brimstone yield per level": "每级硫磺最大产出+1",
    "+15s Soul Stones duration when fed to a familiar": "喂食仆从时，灵魂石持续时间+15秒",
    "+2 actions before switching abilities per level": "每级切换技能前可额外行动次数+2",
    "+2 Soul Stones per level when completing a ritual with 100% path efficiency": "以100%路径效率完成仪式时，每级额外获得灵魂石+2",
    "+5 minutes max familiar time cap": "仆从最大存续时长上限+5分钟",
    "+5% chance per level to find bonus valuables while exhuming": "发掘时每级额外宝物掉落概率+5%",
    "Augury": "占卜术",
    "Avg Efficiency": "平均效率",
    "Bone/Click :": "单次点击骨头产出：",
    "Bones": "骨头",
    "Brimstone": "硫磺",
    "Brimstone/Ward :": "守护结界硫磺消耗：",
    "Concentrated Souls": "凝聚灵魂",
    "Correct Picks": "正确选择次数",
    "Dark Pact": "黑暗契约",
    "Demonic Knowledge": "恶魔学识",
    "DETECTION": "探测能力",
    "Dossier Yield  :": "档案产出：",
    "Double Dip! The runner-up was found too!": "双重收获！连带第二名宝物也一并寻获！",
    "Exhume": "发掘",
    "Extended Ritual": "延长仪式",
    "Familiar": "仆从",
    "Find the sweet spot on the dial!\nMaybe you will find a rare relic...": "找准刻度盘上的最佳点位！或许能找到稀有圣物……",
    "Fortified Chalk": "加固粉笔",
    "Grave Looting": "盗墓掘坟",
    "Longest Kill Chain": "最长连杀纪录",
    "NECROMANCER": "死灵法师",
    "Perfect Rituals": "完美仪式",
    "Perfect Transmutation": "完美转化",
    "Potion of Speak With Dead": "亡灵低语药剂",
    "Reveals a random hint line from the optimal path at the start of each ritual": "每场仪式开始时，随机揭示一条最优路径提示",
    "Reveals how many actions remain before the active ability switches": "显示主动技能切换前剩余行动次数",
    "Rituals Completed": "已完成仪式数",
    "Safe cracked!": "宝库破解成功！",
    "Select the highest quality gem": "选择品质最高的宝石",
    "Soul Stone": "灵魂石",
    "Switch Range   :": "切换范围：",
    "Synaptical Potion Base": "突触药剂基础值",
    "The kobold can't keep up!": "狗头人已无力追击！",
    "Treasure Chests Found": "已发现宝箱数量",
    "Vault of Souls": "灵魂密室",
    "Winged Kobold": "翼行狗头人",
    "Wrong — not the finest gem.": "选错——并非最优宝石。",
    "Wrong Picks": "错误选择次数",
    "Annotated Cookbook": "注解食谱",
    "Each round begins with a free hint": "每回合开局可获得一次免费提示",
    "Appraisal complete! (": "鉴定完成！(",
    "Dilution partial! (": "局部稀释！(",
    "Faceting success + Double Dip! (": "雕琢成功 + 双重收获！(",
    "Heist started! (": "劫掠开始！(",
    "Safe cracked! (": "金库破解成功！(",
    "Chest!": "宝箱！",
    "Faceting success! (": "雕琢成功！(",
    "Find Familiar": "寻找仆从",
    "Fine eye for the best, but the runner-up slipped away.": "眼光精准选出最优宝物，次优珍宝却悄然溜走。",
    "Kobold Mountain Lion": "狗头人山狮",
    "Summon a spectral familiar for each character. Feed it Soul Stones for temporary +1 Jack power": "为每个角色召唤一只幽灵仆从。投喂灵魂石可临时提升1点倍率威力。",
    "You defiled the earth and unearthed bones": "你玷污了大地，还挖出了骸骨",
    " Grotesque": "畸形怪",
    " Leader": "首领",
    " Pebble": "小圆石",
    "\"Kobold\" Heart": "「狗头人之心」",
    "[ KOBOLD LEADER ]": "【狗头人首领】",
    "[ Short Rest: ON ]": "【短暂休憩：开启】",
    "// ETCHING": "// 铭刻",
    "// STOCK MARKET": "// 股市行情",
    ">> THE CHIMERA AWAKENS !!! <<": ">> 奇美拉已然苏醒 !!! <<",
    "★ THE CHIMERA AWAKENS! ★": "★ 奇美拉已然苏醒！★",
    "★ THE CHIMERA AWAKENS! The impossible lives!": "★ 奇美拉已然苏醒！虚妄之物，现世降临！",
    "A butterfly flaps its wings, events set in motion cannot be stopped. A tragic tale, with humble beginnings, can you fault him for the death of all those who come after?": "一只蝴蝶振翅扇动翅膀，命运轨迹就此启动，再无逆转余地。一场起于微末的悲剧，世人皆因此殒命，又怎能苛责始作俑者？",
    "Chimeramancer": "奇美拉操控者",
    "Conjured mechanisms autonomized the massacre brought upon the world. If only she rejected perfection once more...": "被召唤的构装机关，肆意屠戮世间生灵。倘若她当初能放下对极致完美的执念……",
    "Construct": "构装造物",
    "Etching Level:": "铭刻等级：",
    "Etchings Completed": "已完成铭刻数",
    "Etchings Failed": "铭刻失败数",
    "Forbidden Tome": "禁断典籍",
    "Gold Spent": "已花费金币",
    "His finest meals gave the chimera its strength. The spices he cherished now burn in its breath. The aromas led the masses to the site of their death.": "他亲手烹制的佳肴赋予了奇美拉力量。他珍视的香料，如今化作巨兽口鼻中燃烧的烈焰。诱人的香气，引众生步入死亡之地。",
    "His potions flow through the chimera's blood and mind. Every elixir he brewed now sustains the abomination. If only they were diluted further...": "他炼制的药剂流淌在奇美拉的血脉与意识之中。每一瓶亲手调配的灵药，如今都在维系这头畸变怪物的存续。若是当初将药剂再加以稀释……",
    "Ichor": "生灵原液",
    "Items Purchased": "已购入物品",
    "Life Thread": "生命丝线",
    "Luxury and craft are no help against the unseen foe. Perhaps his skills were too much for man to handle.": "奢华工艺与精湛技艺，在无形灾厄面前毫无用处。或许他掌握的学识技艺，早已超出凡人所能掌控的界限。",
    "Magical Implement": "魔法器具",
    "Mana": "魔力",
    "Monster Trophy": "魔物战利品",
    "Perhaps some knowledge deserve to remain in the dark.": "有些知识，本就该永远隐匿于黑暗之中。",
    "Relic: Belt of the Woodlands": "遗物：林地腰带",
    "Relic: Chisel of Dwarvenkind": "遗物：矮人凿子",
    "Relic: Clasp of Exquisite Taste": "遗物：雅致品味饰扣",
    "Relic: Crown of Command": "遗物：号令王冠",
    "Relic: Jeweled Hand of the Night": "遗物：暗夜宝石之手",
    "Relic: Ledger of Infinite Commerce": "遗物：无尽商贸账本",
    "Relic: Masterwork Monocle of Perfection": "遗物：精工完美单片镜",
    "Relic: Monocle of Perfect Theurgy": "遗物：至臻神术单片镜",
    "Relic: Relic Hunter": "遗物：遗物猎人",
    "Relic: Ring of Shadows": "遗物：暗影之戒",
    "Relic: Spool of Infinite Weaving": "遗物：无尽编织线轴",
    "Severed from his worldly connection, only the finest procured, only the finest slain by.": "斩断凡尘俗世牵绊，只搜罗世间至珍，只猎杀世间至强。",
    "The bones of the chimera and his breath of brimstone belong not to him. The necromancer among the first to see the dead he loved so much...": "奇美拉的骸骨与硫磺吐息，本非自身所有。死灵术士最先亲眼见证了挚爱之人离世的光景……",
    "The Chimera Awakens!": "奇美拉已然苏醒！",
    "The first to see his creation, the first to be killed by it. Despite this, he seems sickly satisfied as he breathes his final breath...": "他是第一个见证自己造物诞生的人，也是第一个被造物所杀的人。即便如此，咽下最后一口气时，他脸上却带着病态的满足……",
    "The flesh of the beast belongs not to it, delivered and fleshcrafted into an amalgam. This sin represents the body of all beasts, and now, man too.": "巨兽的血肉并非本源所有，经由塑血秘术拼接成混沌聚合体。这份罪孽承载着万兽之躯，如今亦浸染了凡人之身。",
    "Unknown Bead": "未知宝珠",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "-- vs --": "-- vs --",
    "Jacks": "全能型人才",
    "Jack": "全能型人才",
    "____________ _____   _____  _     _____ _____  _   __ ___________\n| ___ \\ ___ \\  __ \\ /  __ \\| |   |_   _/  __ \\| | / /|  ___| ___ \\\n| |_/ / |_/ / |  \\/ | /  \\/| |     | | | /  \\/| |/ / | |__ | |_/ /\n|    /|  __/| | __  | |    | |     | | | |    |    \\ |  __||    /\n| |\\ \\| |   | |_\\ \\ | \\__/\\| |_____| |_| \\__/\\| |\\  \\| |___| |\\ \\\n\\_| \\_\\_|    \\____/  \\____/\\_____/\\___/ \\____/\\_| \\_/\\____/\\_| \\_|": "",
    "--/s": "--/秒",
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "*": "*",
    "───": "───",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "ᛃ": "ᛃ",
    "🌢": "🌢",
    "☠": "☠",
    "⚔": "⚔",
    "_._     _,-'\"\"`-._\n(,-.`._,'(       |\\`-/|\n    `-.-' \\ )-`( , o o)\n          `-    \\`_ ৲\"৲-": "_._     _,-'\"\"`-._\n(,-.`._,'(       |\\`-/|\n    `-.-' \\ )-`( , o o)\n          `-    \\`_ ৲\"৲-",
    "████████░░": "████████░░",
    "██████░░░░": "██████░░░░",
    "████░░░░░░": "████░░░░░░",
    "██░░░░░░░░": "██░░░░░░░░",
    "░░░░░░░░░░": "░░░░░░░░░░",
    "✗": "✗",
    "⍯": "⍯",
    "Ő": "Ő",
    "ᳱ": "ᳱ",
    "ᛗ": "ᛗ",
    "ᛝ": "ᛝ",
    "⌇": "⌇",
    "⌺": "⌺",
    "◈": "◈",
    "♥": "♥",
    "⚙": "⚙",
    "🕱": "🕱",
    "🜏": "🜏",
    "+----------+": "+----------+",
    "🜛": "🜛",
    "💎︎": "💎︎",
    "_": "_",
    "⚱": "⚱",
    "⌸": "⌸",
    "⸙": "⸙",
    "○": "○",
    "৲": "৲",
    "ↀ": "ↀ",
    "Ҩ": "Ҩ",
    ") ]": ") ]",
    "<(>_<)>↟  \n   /||-- |   \n   d  b  |": "<(>_<)>↟  \n   /||-- |   \n   d  b  |",
    "Ф": "Ф",
    "⚗)": "⚗)",
    "♨": "♨",
    "γ": "γ",
    "Δ": "Δ",
    "✦": "✦",
    "⚗": "⚗",
    "Ꮻ": "Ꮻ",
    "♣": "♣",
    "[+]": "[+]",
    "[ □ ] ": "[ □ ] ",
    "[ ■ ] ": "[ ■ ] ",
    "+===============================================================================================+": "+===============================================================================================+",
    "[X]": "[X]",
    "[-]": "[-]",
    "[<]": "[<]",
    "[>]": "[>]",
    "֍": "֍",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': '药剂师',
    'B': 'B',
    'C': '烹饪师',
    'D': 'D',
    'E': 'E',
    'F': '战士',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': '游侠',
    'S': 'S',
    'T': '小偷',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Lv.": "等级",
    "Kobold": "地精",
    "Fermentation Vats upgraded to Lv.": "发酵木桶 升级到等级",
    "Spiced Bait upgraded to Lv.": "香辛诱饵 升级到等级",
    "Insightful Contracts upgraded to Lv.": "洞察力合同 升级到等级",
    "Potion Titration upgraded to Lv.": "药水滴定法 升级到等级",
    "Potion Marketing upgraded to Lv.": "药剂营销 升级到等级",
    "Wholesale Spices upgraded to Lv.": "散装香料 升级到等级",
    "The Slow Blade upgraded to Lv.": "慢刃 升级到等级",
    "Hovel Garden upgraded to Lv.": "小屋菜园 升级到等级",
    "More Herbs upgraded to Lv.": "更多草药 升级到等级",
    "Sharper Swords upgraded to Lv.": "锋利长剑 升级到等级",
    "Better Tracking upgraded to Lv.": "更好的追踪 升级到等级",
    "Potion of Cat's Eye upgraded to Lv.": "猫眼药剂 升级到等级",
    "Extended Ritual upgraded to Lv.": "延长仪式 升级到等级",
    "Dark Pact upgraded to Lv.": "黑暗契约 升级到等级",
    "Baited Traps upgraded to Lv.": "诱饵陷阱 升级到等级",
    " Bait upgraded to Lv.": "诱饵 升级到等级",
    "Better Bounties upgraded to Lv.": "更好的赏金 升级到等级",
    "Contracted Hirelings upgraded to Lv.": "雇佣兵 升级到等级",
    "[SAVE] ": "[保存] ",
    "[AUTO-SAVE] ": "[自动保存] ",
    "A Jack of All Trades has been hired! (Total: ": "一位全能型人才已被聘用！（总计：",
    "⚠ Jack idle — ": "⚠ 全能型人才空闲 — ",
    "[+ HEAL ": "[+ 治疗 ",
    "Final blow: ": "致命一击：",
    "Victory! ": "胜利! ",
    "[ LONG REST: ": "[ 长时间休息: ",
    "Last strike: ": "最后一击：",
    "[ SCOUT (": "[ 侦查 (",
    "[ SCOUT AGAIN (": "[ 再次侦查 (",
    "[ Kobold Bait: ON ] (": "[ 地精诱饵：打开 ]（",
    "[ Kobold Bait: OFF ] (": "[ 地精诱饵：关闭 ]（",
    "Snake Kobold": "蛇地精",
    "Guesses: ": "猜测: ",
    "[ START HEIST (": "[ 开始掠夺 (",
    "[ FACET (": "[ 位面 (",
    "** RECIPE COMPLETE! **": "** 食谱完成! **",
    "First Strike!": "第一击！",
    "[ FACET AGAIN (": "[ 再次位面 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "Bland Mode": "平铺模式",
    "Hide Maxed Upgrades": "隐藏满级的升级",
    " has been unlocked! Welcome to the party.": " 已解锁！欢迎加入队伍。",
    " (RANGER UNLOCK)": " (游侠解锁)",
    " (JACKS UNLOCK)": " (全能型人才解锁)",
    " (APOTHECARY UNLOCK)": " (药剂师解锁)",
    " (CULINARIAN UNLOCK)": " (烹饪师解锁)",
    " (JACKD UP UNLOCK)": " (强化仆从解锁)",
    " (MERCHANT UNLOCK)": " (商人解锁)",
    " (ARTIFICER UNLOCK)": " (艺术家解锁)",
    " (ARTISAN UNLOCK)": " (工匠解锁)",
    " (CHIMERAMANCER UNLOCK)": " (奇美拉巫师解锁)",
    " (NECROMANCER UNLOCK)": " (亡灵法师解锁)",
    " (THIEF UNLOCK)": " (小偷解锁)",
    " (MINIGAME UNLOCK)": " (小游戏解锁)",
    " Unlocked": " 已解锁",
    ". (": ". (",
    " defeated": " 已被击败",
    "% each": "% 每个",
    " CONCENTRATED!": " 集中精力！",
    ": Jack Bead Found": ": 找到人才宝珠",
    ": Blue Bead Found": ": 找到蓝色宝珠",
    ": Gold Bead Found": ": 找到金色宝珠",
    ": Gold Bead Found (Sidequest)": ": 找到金色宝珠 (支线)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\[([\d\.]+)\]$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)⚗$/,
    /^\-([\d\.]+)Ꮻ$/,
    /^\-([\d\.]+)♣$/,
    /^\-([\d\.]+)⌸$/,
    /^\+([\d\.]+)♣$/,
    /^\+([\d\.]+)⚱$/,
    /^\+([\d\.]+)💎︎$/,
    /^\+([\d\.]+)🜛$/,
    /^\+([\d\.]+)Ő$/,
    /^\+([\d\.]+)৲$/,
    /^\+([\d\.]+)✦$/,
    /^\+([\d\.]+)⌸$/,
    /^\+([\d\.]+)Ꮻ$/,
    /^\+([\d\.]+)🌢$/,
    /^\+([\d\.]+)Δ$/,
    /^\+([\d\.]+)🕱$/,
    /^\+([\d\.]+)♣$/,
    /^\+([\d\.]+)γ$/,
    /^\+([\d\.]+)\>$/,
    /^\+([\d\.]+)⚗$/,
    /^\+ ([\d\.]+)$/,
    /^\+([\d\.]+) \(\-([\d\.]+)$/,
    /^\-([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^, \+([\d\.]+)\%$/,
    /^([\d\.]+)× \+ ([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^⚠ 全能(.+)$/,
    /^药剂(.+)$/,
    /^锋利长剑(.+)$/,
    /^更多(.+)$/,
    /^更多(.+)$/,
    /^更好(.+)$/,
    /^雇佣兵(.+)$/,
    /^胜利(.+)$/,
    /^成本(.+)$/,
    /^(.+)经验值\)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)\/([\d\.]+)k$/,
    /^([\d\.]+)k\/([\d\.]+)k$/,
    /^([\d\.]+)\/([\d\.]+)M$/,
    /^([\d\.]+)M\/([\d\.]+)M$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\$$/,
    /^([\d\.,]+)\)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\(\+([\d\.,]+)$/,
    /^\(([\d\.,]+)x, ([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^([\d\.,]+) \- ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You strike the chimera for (.+) damage! \($/, '你攻击奇美拉造成 $1 点伤害！('],
    [/^⚠ Ward Jack idle \— need (.+) XP \(have (.+)\)$/, '⚠ 守护结界 人才空闲 — 需要 $1 经验值 (拥有 $2)'],
    [/^Pointer at (.+)°.$/, '指针在 $1°。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)g$/, '$1 金币'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\-([\d\.]+)\$$/, '-$1$'],
    [/^\-([\d\.]+)\/s$/, '-$1/秒'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)\% assembled$/, '$1% 已组装'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) gold per sec$/, '+$1 金币每秒'],
    [/^\+([\d\.,]+) gold per bounty$/, '+$1 金币每个悬赏'],
    [/^\+([\d\.,]+) XP per bounty completed$/, '+$1 经验每完成一次悬赏'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^ \(\+([\d\.,]+) bonus\)$/, ' (+$1 奖励)'],
    [/^\+([\d\.,]+)֍$/, '+$1 ֍'],
    [/^\+([\d\.,]+)\$$/, '+$1 $'],
    [/^\+([\d\.,]+)\/s$/, '+$1/秒'],
    [/^\+([\d\.,]+)k\/s$/, '+$1k/秒'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\[×([\d\.,]+) Abundant Lands\]$/, '[×$1 丰饶之地]'],
    [/^([\d\.,]+)\/([\d\.,]+) CONCENTRATED  \(([\d\.,]+) BASE\)$/, '$1/$2 浓缩 ($3 基础)'],
    [/^On beat! \+([\d\.,]+) quality \(([\d\.,]+)\/([\d\.,]+)\)$/, '命中！品质 +$1 （$2/$3）'],
    [/^Bubbling hit! \+([\d\.,]+) quality \(([\d\.,]+)\/([\d\.,]+)\)$/, '冒泡打击！品质 +$1 （$2/$3）'],
    [/^([\d\.,]+)s \]$/, '$1秒 ]'],
    [/^need ([\d\.,]+) treasure \(have ([\d\.,]+)\)$/, '需要 $1 宝物 (拥有 $2)'],
    [/^need ([\d\.,]+) gold \(have ([\d\.,]+)\)$/, '需要 $1 金币 (拥有 $2)'],
    [/^need ([\d\.,]+) herbs \(have ([\d\.,]+)\)$/, '需要 $1 草药 (拥有 $2)'],
    [/^ hits ([\d\.,]+)!$/, ' 命中并造成 $1 伤害！'],
    [/^You deal ([\d\.,]+) dmg.$/, '你造成了 $1 伤害。'],
    [/^You heal ([\d\.,]+) HP.$/, '你治疗了 $1 生命值。'],
    [/^([\d\.,]+) gems presented. Choose wisely!$/, '$1 已赠送宝石。请慎重选择！'],
    [/^([\d\.,]+) failed attempt marked.$/, '$1 次失败尝试已标记。'],
    [/^([\d\.,]+) failed attempts marked.$/, '$1 次失败尝试已标记。'],
    [/^([\d\.,]+) dmg!$/, '$1 伤害!'],
    [/^ ([\d\.,]+) dmg!$/, ' $1 伤害!'],
    [/^ Mountain Lion hits ([\d\.,]+)!$/, ' 山狮造成 $1 伤害！'],
    [/^\[ CHAIN x([\d\.,]+)! \]$/, '[ 链接 x$1！]'],
    [/^\[×([\d\.,]+) Abundant Lands\] Ranger scouted the area$/, '[×$1 丰饶之地] 游侠侦查了这片区域'],
    [/^XP ([\d\.,]+)$/, '经验值 $1'],
    [/^([\d\.,]+) correct, ([\d\.,]+) misplaced. ([\d\.,]+) left.$/, '$1 正确，$2 错误。剩余 $3。'],
    [/^Guess the recipe! ([\d\.,]+) attempts.$/, '猜猜这个配方吧！有 $1 次机会。'],
    [/^\[ FLEEING... ([\d\.,]+)s \]$/, '[ 逃跑中... $1秒 ]'],
    [/^\(\+([\d\.,]+) XP\)$/, '(+$1 经验值)'],
    [/^\(([\d\.,]+) symbols\)$/, '($1 符号)'],
    [/^Need ([\d\.,]+)🕱, ([\d\.,]+)🜏$/, '需要 $1🕱, $2🜏'],
    [/^Need ([\d\.,]+)💎︎, ([\d\.,]+)🕱, ([\d\.,]+)🜏$/, '需要 $1💎︎, $2🕱, $3🜏'],
    [/^need ([\d\.,]+) more$/, '还需要 $1'],
    [/^\xa0 Won in ([\d\.,]+) guesses$/, ' 获胜于 $1 次尝试'],
    [/^\xa0 Won in ([\d\.,]+) guess$/, ' 获胜于 $1 次尝试'],
    [/^Costs ([\d\.,]+)$/, '成本 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);